# Tensors 

In [1]:
import torch
print(torch.__version__)

2.4.0+cu118


In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

## zeros()

In [11]:
w = torch.zeros(4, 3)

In [12]:
w

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

## size() and shape

In [13]:
w.size()

torch.Size([4, 3])

In [14]:
w.shape

torch.Size([4, 3])

## randn() and randn_like()

In [15]:
w = torch.randn(4, 3)
w

tensor([[ 1.3528, -0.1761, -0.4643],
        [-0.5252, -1.0220, -1.0220],
        [-0.0368,  0.7938, -1.3044],
        [ 1.2002, -0.0729,  0.4665]])

In [16]:
t = torch.randn_like(w)
t

tensor([[-1.3506,  0.1968, -1.5002],
        [ 0.1708, -0.3420, -0.6782],
        [-0.4962,  1.5431, -0.8925],
        [ 0.6340, -3.3526,  0.2988]])

## fill_()

In [17]:
w.fill_(1)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [18]:
w

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

## view()

In [19]:
w.view(3, 4)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [20]:
w.view(2, -1)

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [21]:
w.view(1, -1)

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## numpy()

In [24]:
na = w.numpy()
na

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [25]:
type(w), type(na)

(torch.Tensor, numpy.ndarray)